### ISSUE TITLE
Git command retrieves the `develop` branch

### ISSUE THREAD

**Issue by InMatrix** [material-components/material-components-flutter-motion-codelab#27]
On [page three](https://codelabs.developers.google.com/codelabs/material-motion-flutter/#2) of the codelab, there is an option to download the starter app using this git command `git clone https://github.com/material-components/material-components-flutter-motion-codelab.git`. However, the resulting repo will be on the default `develop` branch, which has nothing but a readme file. I think this command needs to specify the `starter` branch instead.

**Comment by Renzo-Olivares** [comment]
@guidezpl I think the `develop` branch should be removed. It was replaced in favor of `starter`.  The default branch should also be changed to `starter` so it is pulled by default.

**Comment by guidezpl** [comment]
Agreed, this has been fixed
