### ISSUE TITLE
'TransitionBuilderPage' shows error

### ISSUE THREAD

**Issue by karthickramanathan95** [material-components/material-components-flutter-motion-codelab#28]
TransitionBuilderPage shows error in starter branch in router.dart and mail_view_router.dart.

What to do?

![image](https://user-images.githubusercontent.com/30870272/94919493-2f693780-04d2-11eb-8a07-fa44f7bb158d.png)

**Comment by fernandoarrj** [comment]
Hey man.

I had to put the dev channel.

flutter channel dev
flutter uprade

Now works.

**Comment by karthickramanathan95** [comment]
It is working, thanks, I am closing the issue.
