### ISSUE TITLE
Prefer to use TransitionBuilderPage or equivalent over custom solution

### ISSUE THREAD

**Issue by Renzo-Olivares** [material-components/material-components-flutter-motion-codelab#32]
#30 and #31 move away from using `TransitionBuilderPage` since it has not landed in stable and was recently removed from master https://github.com/flutter/flutter/pull/66694 . Revisit the implementation in these PR's once `TransitionBuilderPage` or the equivalent has been pushed to stable.

**Comment by israe1** [comment]
Hi sir.
I'm on the beta channel and I'm getting this error when trying to build the material-components-flutter-motion-codelab

`lib/router.dart:50:15: Error: The method 'TransitionBuilderPage' isn't defined for the class 'ReplyRouterDelegate'.`

**Comment by Renzo-Olivares** [comment]
> Hi sir.
> I'm on the beta channel and I'm getting this error when trying to build the material-components-flutter-motion-codelab
> 
> `lib/router.dart:50:15: Error: The method 'TransitionBuilderPage' isn't defined for the class 'ReplyRouterDelegate'.`

Hello,

The issue you are referring to is now fixed. Try doing a `git pull` to get the latest changes.

**Comment by israe1** [comment]
Thanks a lot.
