### ISSUE TITLE
Github repo link is pointing to the android repository

### ISSUE THREAD

**Issue by alizera** [material-components/material-components-flutter-motion-codelab#43]
At step 3, Option 1, the link id directing to https://github.com/material-components/material-components-android-motion-codelab while it should go to https://github.com/material-components/material-components-flutter-motion-codelab.

![image](https://user-images.githubusercontent.com/50444607/125806235-7072dabb-d833-48b9-9afc-1cfc52bff2a1.png)

**Comment by guidezpl** [comment]
Thanks for noticing, this has been fixed
